/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import Model.CauHoi;
import Model.CauHoiTL;
import Model.CauHoiTN;
import ModelMonHoc.DeThi;
import ThaoTac.FileTypeFilter;
import ThaoTac.LayDuLieu;
import ThaoTac.LuuDanhSachMonHocRaNgoai;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author CaoThienHUST
 */
public class GiaoDienSoanDeThi extends javax.swing.JFrame {

    private LayDuLieu duLieu;
    //Lấy dữ liệu hệ thông
    private int indexMonHoc;
    //Vị trí xác định môn học nào được chọn
    private ArrayList<CauHoi> dsCauHoiGoc;
    //Mảng câu hỏi lấy từ môn học
    private ArrayList<CauHoi> dsCauHoiChonVaoDe = new ArrayList<>();
    //Mảng câu hỏi đã được chọn để cho vào đề
    private ArrayList<CauHoi> dsCauHoiTrenList;
    //Mảng câu hỏi để hiển thị trên Jlist đã được phân loại
    /**
     * Creates new form SoanDeThi
     */
    public GiaoDienSoanDeThi(int indexMonHoc) {
        this.setLocation(300, 300);
        initComponents();
        this.indexMonHoc = indexMonHoc;
        duLieu = new LayDuLieu();
        dsCauHoiGoc = duLieu.getDanhSachMonHoc().get(indexMonHoc).getArrCauHoi();
//        String[] listCauHoi=duLieu.toArrayStringDsCauHoi(indexMonHoc);
//        jListDanhSachCauHoi.setListData(listCauHoi);
        dsCauHoiTrenList = phanLoaiCauHoiTheoDoKhoVaChuong(dsCauHoiGoc, jComboBoxDoKho.getSelectedIndex(), jComboBoxChuong.getSelectedIndex());
        jListDanhSachCauHoi.setListData(toStringDsCauHoi(dsCauHoiTrenList));
        jLabelTenMon.setText("Danh sách câu hỏi môn: "+duLieu.getDanhSachMonHoc().get(indexMonHoc).getTenMonHoc());
        jLabelThongTinSoCauHoi.setText("Tổng số câu hỏi là: "+duLieu.getDanhSachMonHoc().get(indexMonHoc).getArrCauHoi().size());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupDoKho = new javax.swing.ButtonGroup();
        jSpinner1 = new javax.swing.JSpinner();
        buttonGroupLoaiDe = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListDanhSachCauHoi = new javax.swing.JList<>();
        jLabelTenMon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxDoKho = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxChuong = new javax.swing.JComboBox<>();
        jButtonSinhDeTuDong = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListCauHoiChoVaoDe = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButtonTN = new javax.swing.JRadioButton();
        jRadioButtonTL = new javax.swing.JRadioButton();
        jRadioButtonTongHop = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldTenDeThi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButtonLuu = new javax.swing.JButton();
        jButtonHuy = new javax.swing.JButton();
        jButtonThemCauHoi = new javax.swing.JButton();
        jLabelXoaCauHoiDaChon = new javax.swing.JLabel();
        jLabelXaoTronCauHoi = new javax.swing.JLabel();
        jTextFieldSoCau = new javax.swing.JTextField();
        jLabelThongTinSoCauHoi = new javax.swing.JLabel();
        jButtonXuatRaFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jListDanhSachCauHoi);

        jLabelTenMon.setText("Danh sách câu hỏi môn:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Soạn đề thi");

        jLabel3.setText("Độ khó");

        jComboBoxDoKho.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jComboBoxDoKho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trung Bình ", "Khá", "Giỏi" }));
        jComboBoxDoKho.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxDoKhoItemStateChanged(evt);
            }
        });

        jLabel4.setText("Chương:");

        jComboBoxChuong.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jComboBoxChuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chương 1", "Chương 2", "Chương 3", "Chương 4" }));
        jComboBoxChuong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxChuongItemStateChanged(evt);
            }
        });

        jButtonSinhDeTuDong.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButtonSinhDeTuDong.setText("Sinh Đề Tự Động");
        jButtonSinhDeTuDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSinhDeTuDongActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(jListCauHoiChoVaoDe);

        jLabel5.setText("Chọn thuộc tính đề thi:");

        jLabel6.setText("Loại đề:");

        buttonGroupLoaiDe.add(jRadioButtonTN);
        jRadioButtonTN.setText("Trắc nghiệm");

        buttonGroupLoaiDe.add(jRadioButtonTL);
        jRadioButtonTL.setText("Tự luận");

        buttonGroupLoaiDe.add(jRadioButtonTongHop);
        jRadioButtonTongHop.setText("Tổng hợp");

        jLabel7.setText("Tên đề:");

        jLabel8.setText("Số câu:");

        jButtonLuu.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButtonLuu.setText("Save");
        jButtonLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLuuActionPerformed(evt);
            }
        });

        jButtonHuy.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButtonHuy.setText("Back");
        jButtonHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHuyActionPerformed(evt);
            }
        });

        jButtonThemCauHoi.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButtonThemCauHoi.setText("Thêm Câu Hỏi");
        jButtonThemCauHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemCauHoiActionPerformed(evt);
            }
        });

        jLabelXoaCauHoiDaChon.setForeground(new java.awt.Color(255, 0, 51));
        jLabelXoaCauHoiDaChon.setText("Xóa câu hỏi");
        jLabelXoaCauHoiDaChon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 153)));
        jLabelXoaCauHoiDaChon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelXoaCauHoiDaChonMouseClicked(evt);
            }
        });

        jLabelXaoTronCauHoi.setForeground(new java.awt.Color(255, 51, 51));
        jLabelXaoTronCauHoi.setText("Xáo trộn câu");
        jLabelXaoTronCauHoi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jLabelXaoTronCauHoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelXaoTronCauHoiMouseClicked(evt);
            }
        });

        jLabelThongTinSoCauHoi.setText("Tổng số câu hỏi là: ");

        jButtonXuatRaFile.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButtonXuatRaFile.setText("Xuất ra file  ");
        jButtonXuatRaFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXuatRaFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelThongTinSoCauHoi)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTenMon)
                                .addGap(333, 333, 333)
                                .addComponent(jLabel2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBoxDoKho, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBoxChuong, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonThemCauHoi))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jRadioButtonTN)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButtonTL)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButtonTongHop))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel8))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextFieldTenDeThi)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jTextFieldSoCau, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, Short.MAX_VALUE)))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelXaoTronCauHoi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonSinhDeTuDong)
                                        .addGap(83, 83, 83)
                                        .addComponent(jLabelXoaCauHoiDaChon))
                                    .addComponent(jScrollPane3))))
                        .addGap(20, 20, 20))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonXuatRaFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLuu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonHuy)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTenMon)
                    .addComponent(jLabel2))
                .addGap(3, 3, 3)
                .addComponent(jLabelThongTinSoCauHoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelXoaCauHoiDaChon)
                                .addGap(5, 5, 5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonSinhDeTuDong)
                                    .addComponent(jLabelXaoTronCauHoi))))
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jRadioButtonTN)
                            .addComponent(jRadioButtonTL)
                            .addComponent(jRadioButtonTongHop)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldTenDeThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonThemCauHoi)
                    .addComponent(jComboBoxChuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxDoKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldSoCau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonXuatRaFile)
                    .addComponent(jButtonLuu)
                    .addComponent(jButtonHuy)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxDoKhoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxDoKhoItemStateChanged
        // TODO add your handling code here:
        int chuong = jComboBoxChuong.getSelectedIndex();
        dsCauHoiTrenList = phanLoaiCauHoiTheoDoKhoVaChuong(dsCauHoiGoc, jComboBoxDoKho.getSelectedIndex(), chuong);
        jListDanhSachCauHoi.setListData(toStringDsCauHoi(phanLoaiCauHoiTheoDoKhoVaChuong(dsCauHoiGoc, jComboBoxDoKho.getSelectedIndex(), chuong)));
    }//GEN-LAST:event_jComboBoxDoKhoItemStateChanged

    private void jComboBoxChuongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxChuongItemStateChanged
        // TODO add your handling code here:
        int doKho = jComboBoxDoKho.getSelectedIndex();
        dsCauHoiTrenList = phanLoaiCauHoiTheoDoKhoVaChuong(dsCauHoiGoc, doKho, jComboBoxChuong.getSelectedIndex());
        jListDanhSachCauHoi.setListData(toStringDsCauHoi(phanLoaiCauHoiTheoDoKhoVaChuong(dsCauHoiGoc, doKho, jComboBoxChuong.getSelectedIndex())));

    }//GEN-LAST:event_jComboBoxChuongItemStateChanged

    private void jButtonThemCauHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemCauHoiActionPerformed
        // TODO add your handling code here:
        if (jListDanhSachCauHoi.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn cấu hỏi cần cho vào đề");

        } else {
            int indexCauHoi = jListDanhSachCauHoi.getSelectedIndex();
            dsCauHoiChonVaoDe.add(dsCauHoiTrenList.get(indexCauHoi));
            jListCauHoiChoVaoDe.setListData(toStringDsCauHoi(dsCauHoiChonVaoDe));
        }
   
    }//GEN-LAST:event_jButtonThemCauHoiActionPerformed

    private void jLabelXoaCauHoiDaChonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelXoaCauHoiDaChonMouseClicked
        // TODO add your handling code here:
        if (jListCauHoiChoVaoDe.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn cấu hỏi cần xóa");
        } else {
            int indexCauHoiMuonXoa = jListCauHoiChoVaoDe.getSelectedIndex();
            dsCauHoiChonVaoDe.remove(indexCauHoiMuonXoa);
            jListCauHoiChoVaoDe.setListData(toStringDsCauHoi(dsCauHoiChonVaoDe));
        }
    }//GEN-LAST:event_jLabelXoaCauHoiDaChonMouseClicked

    private void jButtonHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHuyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonHuyActionPerformed

    private void jLabelXaoTronCauHoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelXaoTronCauHoiMouseClicked
        // TODO add your handling code here:
        ArrayList<CauHoi> dsCauHoiCanXaoTron = new ArrayList<>();
        dsCauHoiCanXaoTron.addAll(dsCauHoiChonVaoDe);
        dsCauHoiChonVaoDe.clear();
        Random rd = new Random();
        Boolean isTrue = true;
        Vector<Integer> vector = new Vector<>();
        for (int i = 0; i < dsCauHoiCanXaoTron.size(); i++) {
            while (isTrue) {
                int inew = rd.nextInt(dsCauHoiCanXaoTron.size());
                if (!vector.contains(inew)) {
                    vector.add(inew);
                    dsCauHoiChonVaoDe.add(dsCauHoiCanXaoTron.get(inew));
                    //System.out.println(inew);
                    isTrue = false;
                }
            }
            isTrue = true;
        }
        jListCauHoiChoVaoDe.setListData(toStringDsCauHoi(dsCauHoiChonVaoDe));
    }//GEN-LAST:event_jLabelXaoTronCauHoiMouseClicked

    private void jButtonSinhDeTuDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSinhDeTuDongActionPerformed
        // TODO add your handling code here:
        dsCauHoiChonVaoDe.clear();
        if (jTextFieldSoCau.getText().isEmpty() || (!(jRadioButtonTL.isSelected() || jRadioButtonTN.isSelected() || jRadioButtonTongHop.isSelected()))) {
            if (jTextFieldSoCau.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Bạn chưa chọn số lượng câu hỏi cho đề thi");
            }
            if ((!(jRadioButtonTL.isSelected() || jRadioButtonTN.isSelected() || jRadioButtonTongHop.isSelected()))) {
                JOptionPane.showMessageDialog(null, "Bạn chưa chọn kiểu đề thi");
            }
        } else {
            
            
            int soCau = Integer.valueOf(jTextFieldSoCau.getText());
            if(soCau>dsCauHoiGoc.size()){
                JOptionPane.showMessageDialog(null, "Số lượng cậu hỏi hiện tại không đủ");
            }
            
            boolean kiemTraSoCauHoiTN;
            boolean kiemTraSoCauHoiTL;
            boolean kiemTraSoCauHoiTongHop;
            Random rd = new Random();
            Boolean isTrue = true;
            Vector<Integer> vector = new Vector<>();
            if (jRadioButtonTN.isSelected()) {
                if (phanLoaiDeTheoKieuCauHoi(dsCauHoiGoc, 1).size() <= soCau) {
                    JOptionPane.showMessageDialog(null, "Số câu hỏi bạn chọn vượt quá số câu hỏi hiện có");
                } else {
                    for (int i = 0; i < soCau; i++) {
                        while (isTrue) {
                            int inew = rd.nextInt(phanLoaiDeTheoKieuCauHoi(dsCauHoiGoc, 1).size());
                            if (!vector.contains(inew)) {
                                vector.add(inew);
                                dsCauHoiChonVaoDe.add(phanLoaiDeTheoKieuCauHoi(dsCauHoiGoc, 1).get(inew));
                                //System.out.println(inew);
                                isTrue = false;
                            }
                        }
                        isTrue = true;
                    }
                }
            } else if (jRadioButtonTL.isSelected()) {
                for (int i = 0; i < soCau; i++) {
                    while (isTrue) {
                        int inew = rd.nextInt(phanLoaiDeTheoKieuCauHoi(dsCauHoiGoc, 2).size());
                        if (!vector.contains(inew)) {
                            vector.add(inew);
                            dsCauHoiChonVaoDe.add(phanLoaiDeTheoKieuCauHoi(dsCauHoiGoc, 2).get(inew));
                            //System.out.println(inew);
                            isTrue = false;
                        }
                    }
                    isTrue = true;
                }
            } else if (jRadioButtonTongHop.isSelected()) {
                for (int i = 0; i < soCau; i++) {
                    while (isTrue) {
                        int inew = rd.nextInt(dsCauHoiGoc.size());
                        if (!vector.contains(inew)) {
                            vector.add(inew);
                            dsCauHoiChonVaoDe.add(dsCauHoiGoc.get(inew));
                            //System.out.println(inew);
                            isTrue = false;
                        }
                    }
                    isTrue = true;
                }
            }
            jListCauHoiChoVaoDe.setListData(toStringDsCauHoi(dsCauHoiChonVaoDe));
        }
    }//GEN-LAST:event_jButtonSinhDeTuDongActionPerformed

    private void jButtonLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLuuActionPerformed
        // TODO add your handling code here:
        if ((jRadioButtonTN.isSelected() || jRadioButtonTL.isSelected() || jRadioButtonTongHop.isSelected()) && !(jTextFieldTenDeThi.getText().isEmpty())&&!(dsCauHoiChonVaoDe.isEmpty())) {
            DeThi dt=new DeThi(jTextFieldTenDeThi.getText(), duLieu.getDanhSachMonHoc().get(indexMonHoc).getTenMonHoc());
            
            ArrayList<CauHoi> dsCauHoi=new ArrayList<>();
            dsCauHoi.addAll(dsCauHoiChonVaoDe);
            dt.setDsCauHoi(dsCauHoi);
            duLieu.getDanhSachMonHoc().get(indexMonHoc).getDsDeThi().add(dt);
//            LayDuLieu dl=new LayDuLieu();
//            dl.getDanhSachMonHoc().get(indexMonHoc).getDsDeThi().add(dt);
            LuuDanhSachMonHocRaNgoai danhSachMonHocRaNgoai=new LuuDanhSachMonHocRaNgoai(duLieu.getDanhSachMonHoc());
            JOptionPane.showMessageDialog(null, "Lưu thành công");
        } else {
            if (!(jRadioButtonTN.isSelected() || jRadioButtonTL.isSelected() || jRadioButtonTongHop.isSelected())) {
                JOptionPane.showMessageDialog(null, "Bạn chưa chọn kiểu đề thi");
            }
            if (jTextFieldTenDeThi.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Bạn chưa điền tên đề thi");
            }
            if(dsCauHoiChonVaoDe.isEmpty()){
                JOptionPane.showMessageDialog(null, "Bạn chưa chọn câu hỏi cho đề thi!!");
            }
        }
//        dsCauHoiChonVaoDe.clear();
//        jListCauHoiChoVaoDe.setListData(toStringDsCauHoi(dsCauHoiChonVaoDe));
        jTextFieldTenDeThi.setText("");
        jTextFieldSoCau.setText("");
//               

    }//GEN-LAST:event_jButtonLuuActionPerformed

    private void jButtonXuatRaFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXuatRaFileActionPerformed
        // TODO add your handling code here:JFileChooser fileChooser=new JFileChooser();
        DeThi dt = new DeThi(jTextFieldTenDeThi.getText(), duLieu.getDanhSachMonHoc().get(indexMonHoc).getTenMonHoc());
        dt.setDsCauHoi(dsCauHoiChonVaoDe);
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setFileFilter(new FileTypeFilter(".doc", "Word file"));
        int res = fileChooser.showSaveDialog(this);
        if (res == fileChooser.APPROVE_OPTION) {

            File f = fileChooser.getSelectedFile();
            try {
                int i = 1;
                FileWriter fw = new FileWriter(f.getPath());
                ArrayList<CauHoi> dsCauHoi = dt.getDsCauHoi();
                for (CauHoi item : dsCauHoi) {
                    fw.write("Câu:" + i + "  " + item.inCauHoi(1) + "\n\n");

                    i++;
                }
                fw.close();
                JOptionPane.showMessageDialog(null, "Xuất file thành công");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Lỗi xuất file");
            }

        }
    }//GEN-LAST:event_jButtonXuatRaFileActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupDoKho;
    private javax.swing.ButtonGroup buttonGroupLoaiDe;
    private javax.swing.JButton jButtonHuy;
    private javax.swing.JButton jButtonLuu;
    private javax.swing.JButton jButtonSinhDeTuDong;
    private javax.swing.JButton jButtonThemCauHoi;
    private javax.swing.JButton jButtonXuatRaFile;
    private javax.swing.JComboBox<String> jComboBoxChuong;
    private javax.swing.JComboBox<String> jComboBoxDoKho;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelTenMon;
    private javax.swing.JLabel jLabelThongTinSoCauHoi;
    private javax.swing.JLabel jLabelXaoTronCauHoi;
    private javax.swing.JLabel jLabelXoaCauHoiDaChon;
    private javax.swing.JList<String> jListCauHoiChoVaoDe;
    private javax.swing.JList<String> jListDanhSachCauHoi;
    private javax.swing.JRadioButton jRadioButtonTL;
    private javax.swing.JRadioButton jRadioButtonTN;
    private javax.swing.JRadioButton jRadioButtonTongHop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextFieldSoCau;
    private javax.swing.JTextField jTextFieldTenDeThi;
    // End of variables declaration//GEN-END:variables
    //Hàm toStringDsCauHoi để chuyển dữ liệu câu hỏi về mảng String để setData cho jList
    private String[] toStringDsCauHoi(ArrayList<CauHoi> dsCauHoi) {
        String[] listCauHoi = new String[dsCauHoi.size()];
        for (int i = 0; i < dsCauHoi.size(); i++) {
            listCauHoi[i] = "Câu " + (i + 1) + ": " + dsCauHoi.get(i).inCauHoi();
        }
        return listCauHoi;
    }
    //Hàm phanLoaiCauHoiTheoDoKhoVaChuong dùng để duyệt lấy ra các câu hỏi thuộc chương ? có độ khó ?
    private ArrayList<CauHoi> phanLoaiCauHoiTheoDoKhoVaChuong(ArrayList<CauHoi> dsCauHoi, int doKho, int chuong) {
        ArrayList<CauHoi> dsCauHoiPhanLoai = new ArrayList<>();
        for (CauHoi item : dsCauHoi) {
            if (item.getDoKho() == (doKho + 1) && item.getChuong() == (chuong + 1)) {
                dsCauHoiPhanLoai.add(item);
            }
        }
        return dsCauHoiPhanLoai;
    }
    // Hàm phanLoaiDeTheoKieuCauHoi duyệt lấy ra các câu hỏi trắc nghiệm hay tự luận
    private ArrayList<CauHoi> phanLoaiDeTheoKieuCauHoi(ArrayList<CauHoi> dsCauHoi, int kieu) {
        ArrayList<CauHoi> dsPhanLoai = new ArrayList<>();
        if (kieu == 1) {
            //Kiểu =1 lấy ra các câu hỏi Trắc nghiệm
            for (CauHoi item : dsCauHoi) {
                if (item instanceof CauHoiTN) {
                    dsPhanLoai.add(item);
                }
            }
        } else if (kieu == 2) {
            //Kiểu =2 lấy ra các câu hỏi Tự Luận
            for (CauHoi item : dsCauHoi) {
                if (item instanceof CauHoiTL) {
                    dsPhanLoai.add(item);
                }
            }
        }
        return dsPhanLoai;
    }
  
}
