/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import Model.CauHoi;
import ModelMonHoc.DeThi;
import ThaoTac.FileTypeFilter;
import ThaoTac.LayDuLieu;
import ThaoTac.LuuDanhSachMonHocRaNgoai;
import java.awt.FileDialog;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CaoThienHUST
 */
public class GiaoDienXuatDeThi extends javax.swing.JFrame {
    private int indexMonHoc;
    private LayDuLieu duLieu;
    
    /**
     * Creates new form GiaoDienLamBaiThi
     */
    public GiaoDienXuatDeThi(int indexMonHoc) {
        this.setLocation(300, 300);
        initComponents();
        this.indexMonHoc=indexMonHoc;
        this.duLieu=new LayDuLieu(indexMonHoc);
        
        String[] listDeThi=duLieu.getDanhSachMonHoc().get(indexMonHoc).toStringDeThi();
        jListDanhSachDeThi.setListData(listDeThi);
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListDanhSachDeThi = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaHienThiDeThi = new javax.swing.JTextArea();
        jButtonXemDeThi = new javax.swing.JButton();
        jButtonXuatDeThi = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnQuayLai = new javax.swing.JButton();
        btnXuatDeTHiCoDapAn = new javax.swing.JButton();
        jLabelTieuDe = new javax.swing.JLabel();
        jTextFieldTieuDe = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jListDanhSachDeThi);

        jLabel1.setText("Danh sách đề thi");

        jTextAreaHienThiDeThi.setColumns(20);
        jTextAreaHienThiDeThi.setRows(5);
        jScrollPane2.setViewportView(jTextAreaHienThiDeThi);

        jButtonXemDeThi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonXemDeThi.setText("Xem Đề Thi");
        jButtonXemDeThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXemDeThiActionPerformed(evt);
            }
        });

        jButtonXuatDeThi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonXuatDeThi.setText("Xuất đề thi không đáp án");
        jButtonXuatDeThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXuatDeThiActionPerformed(evt);
            }
        });

        btnQuayLai.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        btnXuatDeTHiCoDapAn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXuatDeTHiCoDapAn.setText("Xuất đề thi có đáp án");
        btnXuatDeTHiCoDapAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatDeTHiCoDapAnActionPerformed(evt);
            }
        });

        jLabelTieuDe.setText("Tiêu đề: ");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("Xóa đề");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnXuatDeTHiCoDapAn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonXuatDeThi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQuayLai))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonXemDeThi)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelTieuDe)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonXemDeThi)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTieuDe))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonXuatDeThi)
                    .addComponent(btnXuatDeTHiCoDapAn)
                    .addComponent(btnQuayLai))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonXemDeThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXemDeThiActionPerformed
        // TODO add your handling code here:
        if(jListDanhSachDeThi.isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Chọn câu đề thi để xem");
        }else{
            int indexDeThi=jListDanhSachDeThi.getSelectedIndex();
        String dt=duLieu.getDanhSachMonHoc().get(indexMonHoc).getDsDeThi().get(indexDeThi).inDeThi();
        jTextAreaHienThiDeThi.setText(dt);
        }
    }//GEN-LAST:event_jButtonXemDeThiActionPerformed

    private void jButtonXuatDeThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXuatDeThiActionPerformed
        // TODO add your handling code here:
        if(jListDanhSachDeThi.isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Chọn câu đề thi để xuất");
        }else{
            JFileChooser fileChooser=new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setFileFilter(new FileTypeFilter(".doc", "Word file"));
        int res=fileChooser.showSaveDialog(this);
        if(res==fileChooser.APPROVE_OPTION){
            int indexDeThi = jListDanhSachDeThi.getSelectedIndex();
            File f = fileChooser.getSelectedFile();
            try {
                int i = 1;
                FileWriter fw = new FileWriter(f.getPath());
                ArrayList<CauHoi> dsCauHoi = duLieu.getDanhSachMonHoc().get(indexMonHoc).getDsDeThi().get(indexDeThi).getDsCauHoi();
                fw.write("\t\t"+jTextFieldTieuDe.getText()+"\n\n");
                for (CauHoi item : dsCauHoi) {
                    fw.write("Câu:" + i + "  " + item.inCauHoi(1) + "\n\n");
                    
                    i++;
                }
                fw.close();
                JOptionPane.showMessageDialog(null,"Xuất file thành công");
            } catch (IOException ex) {
                Logger.getLogger(GiaoDienXuatDeThi.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        
        }
        
    }//GEN-LAST:event_jButtonXuatDeThiActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnXuatDeTHiCoDapAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatDeTHiCoDapAnActionPerformed
        // TODO add your handling code here:
        if(jListDanhSachDeThi.isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Chọn đề thi để in");
        }else{
            JFileChooser fileChooser=new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setFileFilter(new FileTypeFilter(".doc", "Word file"));
        int res=fileChooser.showSaveDialog(this);
        if(res==fileChooser.APPROVE_OPTION){
            int indexDeThi = jListDanhSachDeThi.getSelectedIndex();
            File f = fileChooser.getSelectedFile();
            try {
                int i = 1;
                FileWriter fw = new FileWriter(f.getPath());
                ArrayList<CauHoi> dsCauHoi = duLieu.getDanhSachMonHoc().get(indexMonHoc).getDsDeThi().get(indexDeThi).getDsCauHoi();
                fw.write("\t\t"+jTextFieldTieuDe.getText()+"\n\n");
                for (CauHoi item : dsCauHoi) {
                    fw.write("Câu:" + i + "  " + item.inCauHoi() + "\n\n");
                    
                    i++;
                }
                fw.close();
                JOptionPane.showMessageDialog(null,"Xuất file thành công");
            } catch (IOException ex) {
                Logger.getLogger(GiaoDienXuatDeThi.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        }
        
    }//GEN-LAST:event_btnXuatDeTHiCoDapAnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jListDanhSachDeThi.isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Chọn câu hỏi muốn xóa");
        }else{
            int indexDeThi=jListDanhSachDeThi.getSelectedIndex();
        LayDuLieu dl=new LayDuLieu();
        dl.getDanhSachMonHoc().get(indexMonHoc).getDsDeThi().remove(indexDeThi);
        LuuDanhSachMonHocRaNgoai luuDanhSachMonHocRaNgoai=new LuuDanhSachMonHocRaNgoai(dl.getDanhSachMonHoc());
        jListDanhSachDeThi.setListData(duLieu.getDanhSachMonHoc().get(indexMonHoc).toStringDeThi());
        }
//        JOptionPane.showMessageDialog(null, "Đã xóa");
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnXuatDeTHiCoDapAn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonXemDeThi;
    private javax.swing.JButton jButtonXuatDeThi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelTieuDe;
    private javax.swing.JList<String> jListDanhSachDeThi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaHienThiDeThi;
    private javax.swing.JTextField jTextFieldTieuDe;
    // End of variables declaration//GEN-END:variables

}
